# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Sourcen holen
      uses: actions/checkout@v3
    - name: JDK 17 bereitstellen
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: maven
    - name: Jar erzeugen
      run: mvn -B package --file pom.xml
    - name: Run Image erzeugen
      run: mvn -B javafx:jlink --file pom.xml
    - name: Installer für Windows erzeugen
      run: mvn -B jpackage:jpackage --file pom.xml
    - name: Publish setup artifact
      uses: actions/upload-artifact@v2
      with:
        name: setup
        path: ${{ github.workspace }}\target\jpackage\*.msi
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
