name: Windows-Build

on:
  push:
    branches:
      - develop
      - main
      - feature*
  pull_request:
    branches:
      - develop
jobs:
  build-windows:
    runs-on:
      - self-hosted
      - windows
    permissions:
      contents: write
      checks: write
    steps:
      - name: Sourcen holen
        uses: actions/checkout@v4
      - name: JDK 17 bereitstellen
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: maven
      - name: Jar erzeugen
        run: mvn -B install --file pom.xml
      - name: Publish setup artifact
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: ${{ github.workspace }}\target\jpackage\*.msi